import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/_theme.scss";
import ThemeToggle from "@/components/atoms/ThemeToggle";
import { NavbarCustom } from "@/components/molecules/Navbar";
import Container from "react-bootstrap/Container";
import { ModalProvider } from "@/components/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ModalProvider>
          <NavbarCustom />
          <Container className="py-4 pt-5 mt-5">{children}</Container>
          <ThemeToggle />
        </ModalProvider>
      </body>
    </html>
  );
}
